package com.msys.digitalwallet.wallet.enums;

public enum ErrorType {
  WALLET_ALREADY_EXISTS,
  WALLET_NOT_EXISTS,
  WALLET_UPDATE_FAILED,
  WALLET_CREATE_FAILED,
  INVALID_IDENTIFIER,

  PLAID_API_FAILED,

  PLAID_WALLET_CREATE_FAILED,
  WALLET_NOT_ACTIVE,
  INSUFFICIENT_BALANCE,

  INVALID_AMOUNT,
  INVALID_CURRENCY
}
