server:
  port: 8090
  servlet:
    context-path: /digital-wallet
spring:
  data:
    mongodb:
      uri: mongodb+srv://digitalwalletdevdb:test1234@digitalcluster.7b5jfat.mongodb.net/?retryWrites=true&w=majority
      database: digitalwallet
      port: 27017
      uuid-representation: STANDARD
  cache:
    type: redis
  application:
    name: springboot-keycloak
  redis:
   host: redis
   port: 6379
#  security:
#      oauth2:
#        resourceserver:
#          jwt:
#            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
#            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#
#  jwt:
#      auth:
#        converter:
#          resource-id: springboot-keycloak-client
#          principal-attribute: preferred_username
services:
  authService:
    baseUrl: http://3.232.225.73:8080
    keycloakBaseUrl: /admin/realms/
    realmsName: SpringBootKeycloak
  notificationService:
    baseUrl: http://notification-service:8081
logging:
  level:
    org:
      springframework:
        web: DEBUG
keycloak:
  admin:
    username: globaladmin
    password: globaladmin
    grantType: password
    clientId: springboot-keycloak-client
    tokenUrl: /realms/SpringBootKeycloak/protocol/openid-connect/token
    serverUrl: http://3.232.225.73:8080
    realmsName: SpringBootKeycloak


plaid:
  environment: sandbox
  clientId: 63f8c212e9b49300135afb5d
  clientSecret: 8e6df9868569fd1777a3e1cbdcfe43
management:
  endpoints:
    web:
      exposure:
        include: [ "health","prometheus", "metrics" ]
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

